baseURL = "http://vedhavyas.com/"
languageCode = "en-us"
title = "Vedhavyas Singareddi"
theme = "minimal"
disqusShortname = "vedhavyas"

[params]
    author = "Vedhavyas Singareddi"
    description = "Distributed Engineer. Gopher. Ployglot. Cyclist"
    githubUsername = "vedhavyas"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "github"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# [[menu.main]]
#     url = "/posts/"
#     name = "Posts"
#     weight = 2
#
# [[menu.main]]
#     url = "/projects/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:vedhavyas@vedhavyas.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/vedhavyas/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/Svedhavyas/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/vedhavyas/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/3563197/vedhavyas"
    name = "stack-overflow"
    weight = 5
